service: scores-highway

provider:
  name: aws
  stage: prd
  region: us-east-2

functions:
  scores-highway:
    name: scores-highway-${self:provider.stage}
    runtime: nodejs12.x
    handler: index.handler
    role: ${opt:role-arn}
    environment:
      CB_PASSWORD: ${opt:cb-password}
      CB_USER_NAME: ${opt:cb-user-name}
      SFTP_HOST: ${opt:sftp-host}
      SFTP_PASSWORD: ${opt:sftp-password}
      SFTP_PATH: ${opt:sftp-path}
      SFTP_USER_NAME: ${opt:sftp-user-name}
    tags:
      version: 1.3.0
    events:
      - schedule:
          rate: cron(0 12 * * ? *)
          enabled: true
    timeout: 600
    vpc:
      securityGroupIds:
        - ${opt:security-group-id}
      subnetIds:
        - ${opt:subnet-id}

plugins:
  - serverless-plugin-include-dependencies
